---
apiVersion: v1
kind: Pod
metadata:
  name: calculator
  labels:
    name: calculator
spec:
  containers:
    - name: mycalc
      image: iad.ocir.io/idxkccw2srke/calc-practice1:${BUILDRUN_HASH}
      imagePullPolicy: Always
      ports:
      - name: calc
        containerPort: 80
        protocol: TCP
  imagePullSecrets:
    - name: secret1

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
     name: calculator
